### ISSUE TITLE
Fase 2 - N3

### ISSUE THREAD

**Issue by jcsporto** [jcsporto/Tasks#23]

**Comment by jcsporto** [comment]
**### Tasks N3**

- [ ] 11.4° - Pomofocus - 25mim - 2 sessões
- [ ] 11.5º - Impacto da musica 
- [ ] 11.6º - Gestão das tarefas no Project
- [ ] 12.1° - Mapa Mental
- [ ] 12.2° - Criar Ruby Gem para cada algoritmo 
- [ ] 12.3° - Rspec gem para teste automatizado
- [ ] 12.4° - Criar um teste Rspec valido p/ todos os algoritmo do N1
- [ ] 13.1° - Pesquisar Problemas em Ingles
- [ ]
